# DoE | Planejando Experimentos com Python

Nesta atividade, vamos gerar diferentes planos experimentais.

Para tal, utilizaremos a biblioteca `pyDOE2` ([informações](https://pypi.org/project/pyDOE2/) e [documentação](https://pythonhosted.org/pyDOE/)).

O Colab não vem com essa biblioteca pré-instalada, então Vamos começar instalando essa biblioteca usando o `pip`.

### Antes de começar: Instale o `pyDOE2` usando o pip.
Dica: No Colab, temos que colocar um sinal de `!` antes do `pip`, assim: `!pip`

In [3]:
# seu código
!pip install pyDOE2


[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Após instalar a biblioteca, importe-a e importe também as suas dependências `numpy`e `scipy`:

In [4]:
# seu código
import pandas as pd
import numpy as np
import scipy
import pyDOE2 as doe

# Geração de Matrizes de Projeto

O pyDOE2 permite criar matrizes de projeto que definem as configurações dos fatores experimentais a serem testados. A  biblioteca suporta vários tipos de matrizes, incluindo:

* **Fatoriais completos**: gera uma matriz de todos os possíveis níveis de todos os fatores.
* **Fatoriais fracionados**: gera uma matriz de uma fração dos níveis possíveis para todos os fatores, reduzindo o número total de configurações a serem testadas.

Vamos praticar ao longo das atividades a seguir:

### Atividade 1: Fatorial Completo de 3 Fatores e 2 Níveis

Nesta abordagem pode haver **apenas dois níveis** por fator.
Esses valores serão representados pelos valores `1` e `-1`.

Dica: Para Fatorial Completo de 2 Níveis, utilizaremos a função `ff2n`.

In [5]:
# seu código
teste = doe.ff2n(3)
print(len(teste))
print(teste)

8
[[-1. -1. -1.]
 [ 1. -1. -1.]
 [-1.  1. -1.]
 [ 1.  1. -1.]
 [-1. -1.  1.]
 [ 1. -1.  1.]
 [-1.  1.  1.]
 [ 1.  1.  1.]]


**PERGUNTA:** Quantas configurações serão testadas no experimento?

>   **RESPOSTA:** ____8___

## Atividade 2: Fatorial Completo (mais de 2 níveis)
Nesta abordagem, pode haver **mais que apenas 2 níveis por fator**, permitindo maior flexibilidade. No entanto, isso irá aumentar a complexidade do experimento.

Crie um Design Fatorial Completo com 3 fatores, com a seguinte configuração:
* O primeiro fator tem 3 níveis;
* O segundo fator tem 2 níveis;
* O terceiro fator tem 4 níveis;

Dica: para Fatorial Completo Geral, utilizaremos a função `fullfact`.



In [6]:
# seu código
plan=[3,2,4]
design = doe.fullfact(plan)
print(design)

[[0. 0. 0.]
 [1. 0. 0.]
 [2. 0. 0.]
 [0. 1. 0.]
 [1. 1. 0.]
 [2. 1. 0.]
 [0. 0. 1.]
 [1. 0. 1.]
 [2. 0. 1.]
 [0. 1. 1.]
 [1. 1. 1.]
 [2. 1. 1.]
 [0. 0. 2.]
 [1. 0. 2.]
 [2. 0. 2.]
 [0. 1. 2.]
 [1. 1. 2.]
 [2. 1. 2.]
 [0. 0. 3.]
 [1. 0. 3.]
 [2. 0. 3.]
 [0. 1. 3.]
 [1. 1. 3.]
 [2. 1. 3.]]


**PERGUNTA:** Quantas configurações serão testadas no experimento?

In [7]:
# seu código
print(len(design))

24


  > **RESPOSTA:** ____24___

## Atividade 3: Fatorial Completo de 3 Fatores e 2 Níveis (parte 2)

Suponha que para a produção de um bolo pronto, desejemos testar os seguintes fatores e níveis:

**Fator 1 | Farinha:**
Tipo 1 ou Tipo 2

**Fator 2 | Quantidade de Fermento:**
24mg ou 36mg

**Fator 3 | Temperatura:**
140ºC ou 180ºC

**INSTRUÇÕES:**

**A.** Gere o plano experimental de fatorial completo utilizando o pyDOE2

**B.** A partir do resultado, crie um DataFrame com o plano expermental, substituindo os valores *1* e *-1* pelos valores reais a serem testados.

In [8]:
# seu código
plan = [2,2,2] 
design = doe.fullfact(plan) 

In [9]:
D = design.copy() 

# Fator 1
D[:,0][D[:,0]==1] = 2
D[:,0][D[:,0]==0] = 1

# Fator 2
D[:,1][D[:,1]==0] = 24
D[:,1][D[:,1]==1] = 36

# Fator 3
D[:,2][D[:,2]==0] = 140
D[:,2][D[:,2]==1] = 180

In [10]:
df = pd.DataFrame(data={'Farinha':D[:,0],'Qtd_Fermento':D[:,1],'Temperatura':D[:,2]})

In [11]:
display(df)

Farinha  Qtd_Fermento  Temperatura
0      1.0          24.0        140.0
1      2.0          24.0        140.0
2      1.0          36.0        140.0
3      2.0          36.0        140.0
4      1.0          24.0        180.0
5      2.0          24.0        180.0
6      1.0          36.0        180.0
7      2.0          36.0        180.0

## Atividade 4: Fatorial Fracionado de 3 Fatores e 2 Níveis

Suponha que antes de rodar um experimento mais complexo como o proposto anteriormente, você decida fazer uma rodada preliminar e mais simples. Assim, você decidirá se os Fatores escolhidos (Tipo da Farinha, Quantidade de Fermento e Temperatura do Forno) aparentam ter de fato algum efeito significativo sobre o sabor do bolo.

Para tal, você decidiu optar por um desenho experimental com apenas 4 experimentos, em vez dos 8 experimentos anteriores.

### Atividade 4.1: Gere um desenho Fatorial Fracionado de 3 Fatores e 2 Níveis

In [12]:
# seu código
gen = 'A B AB'
design0 = doe.fracfact(gen)
display(design0)


array([[-1., -1.,  1.],
       [ 1., -1., -1.],
       [-1.,  1., -1.],
       [ 1.,  1.,  1.]])

**Fator 1 | Farinha:**
Tipo 1 ou Tipo 2

**Fator 2 | Quantidade de Fermento:**
24mg ou 36mg

**Fator 3 | Temperatura:**
140ºC ou 180ºC

In [13]:
D = design0.copy()
# Fator 1
D[:,0][D[:,0]==1] = 2
D[:,0][D[:,0]==-1] = 1

# Fator 2
D[:,1][D[:,1]==-1] = 24
D[:,1][D[:,1]==1] = 36

# Fator 3
D[:,2][D[:,2]==1] = 140
D[:,2][D[:,2]==-1] = 180

### Atividade 4.2: Crie um DataFrame com os valores das variáveis a serem testadas no experimento anterior

In [14]:
df2 = pd.DataFrame(data={'Farinha':D[:,0],'Qtd_Fermento':D[:,1],'Temperatura':D[:,2]})
display(df2)


Farinha  Qtd_Fermento  Temperatura
0      1.0          24.0        140.0
1      2.0          24.0        180.0
2      1.0          36.0        180.0
3      2.0          36.0        140.0

### Atividade 4.3: Invertendo as combinações do Fatorial Fracionado

Suponha que uma colega de equipe com mais experiência em produtos dessa categoria pede que no plano experimental seja contemplada uma combinação específica, não prevista inicialmente. A combinação é a seguinte:

**Farinha:** Tipo 2

**Quantidade de Fermento:** 36mg

**Temperatura:** 180ºC

Adapte o plano experimental de forma que o número de combinações (unidades experimentais) se mantenha o mesmo (4), mas que seja possível testar a combinação proposta.

Dica: Consulte a documentação do pyDOE2 neste [link](https://pythonhosted.org/pyDOE/factorial.html)

In [15]:
# seu código
gen = 'A B -AB'
design0 = doe.fracfact(gen)
display(design0)


array([[-1., -1., -1.],
       [ 1., -1.,  1.],
       [-1.,  1.,  1.],
       [ 1.,  1., -1.]])

In [16]:
# seu código
D = design0.copy()
# Fator 1
D[:,0][D[:,0]==1] = 2
D[:,0][D[:,0]==-1] = 1

# Fator 2
D[:,1][D[:,1]==-1] = 24
D[:,1][D[:,1]==1] = 36

# Fator 3
D[:,2][D[:,2]==1] = 140
D[:,2][D[:,2]==-1] = 180

In [17]:
# seu código
df3 = pd.DataFrame(data={'Farinha':D[:,0],'Qtd_Fermento':D[:,1],'Temperatura':D[:,2]})
display(df3)


Farinha  Qtd_Fermento  Temperatura
0      1.0          24.0        180.0
1      2.0          24.0        140.0
2      1.0          36.0        140.0
3      2.0          36.0        180.0

## Atividade 5

Suponha que a rodada experimental inicial teve resultados bastante proveitosos e foi possível concluir que as Farinhas dos tipos 1 e 2 (ambas super premium) são praticamente iguais. Assim, optar-se-á pela Farinha do tipo 1, que tem um valor mais baixo.

Também percebeu-se que a temperatura de 140ºC foi insuficiente em todos os casos. Assim, decidiu-se testar as temperaturas de 160ºC e de 180ºC.

De modo geral, a rodada inicial correu bem e rapidamente. Por isso, a equipe resolveu incluir outros fatores que não haviam sido testados anteriormente.

Na segunda rodada, serão testados os seguintes fatores:

**A) Quantidade de Fermento:**
24mg ou 36mg

**B) Temperatura:**
160ºC ou 180ºC

**C) Tempo:**
35min ou 40min

**D) Ovos:**
3 ou 4

### Atividade 5.1: Faça uma estimativa de quantos testes seriam necessários para testar todas as possibilidades

In [18]:
# seu código
plan = [2,2,2,2]
design1 = doe.fullfact(plan)
len(design1)

16

> **RESPOSTA:** ___16____

### Atividade 5.2: Crie um desenho fatorial fracionado
Crie um plano experimental para os fatores listados acima de forma que sejam testadas apenas 8 receitas:

**A) Quantidade de Fermento:**
24mg ou 36mg

**B) Temperatura:**
160ºC ou 180ºC

**C) Tempo:**
35min ou 40min

**D) Ovos:**
3 ou 4

In [19]:
# seu código
gen = 'A B C ABC'
design0 = doe.fracfact(gen)
display(design0)
print(len(design0))

array([[-1., -1., -1., -1.],
       [ 1., -1., -1.,  1.],
       [-1.,  1., -1.,  1.],
       [ 1.,  1., -1., -1.],
       [-1., -1.,  1.,  1.],
       [ 1., -1.,  1., -1.],
       [-1.,  1.,  1., -1.],
       [ 1.,  1.,  1.,  1.]])

8


In [20]:
# seu código
D = design0.copy()
# Fator 1
D[:,0][D[:,0]==-1] = 24
D[:,0][D[:,0]==1] = 36

# Fator 2
D[:,1][D[:,1]==-1] = 160
D[:,1][D[:,1]==1] = 180

# Fator 3
D[:,2][D[:,2]==-1] = 35
D[:,2][D[:,2]==1] = 40

# Fator 4
D[:,3][D[:,3]==-1] = 3
D[:,3][D[:,3]==1] = 4

In [21]:
display(D)
print(len(D))

array([[ 24., 160.,  35.,   3.],
       [ 36., 160.,  35.,   4.],
       [ 24., 180.,  35.,   4.],
       [ 36., 180.,  35.,   3.],
       [ 24., 160.,  40.,   4.],
       [ 36., 160.,  40.,   3.],
       [ 24., 180.,  40.,   3.],
       [ 36., 180.,  40.,   4.]])

8


### Extra: Teste outras configurações, compare os dataframes gerados

Há várias maneiras de gerar os desenhos experimentais.
Sugestão: compare os dataframes utilizando a função `concat` do pandas.

In [22]:
# seu código
gen = 'A B C -ABC'
design1 = doe.fracfact(gen)

In [23]:
# seu código
D2 = design1.copy()
# Fator 1
D2[:,0][D2[:,0]==-1] = 24
D2[:,0][D2[:,0]==1] = 36

# Fator 2
D2[:,1][D2[:,1]==-1] = 160
D2[:,1][D2[:,1]==1] = 180

# Fator 3
D2[:,2][D2[:,2]==-1] = 35
D2[:,2][D2[:,2]==1] = 40

# Fator 4
D2[:,3][D2[:,3]==-1] = 3
D2[:,3][D2[:,3]==1] = 4

In [24]:
display(D,D2)
print(len(D),len(D2))

array([[ 24., 160.,  35.,   3.],
       [ 36., 160.,  35.,   4.],
       [ 24., 180.,  35.,   4.],
       [ 36., 180.,  35.,   3.],
       [ 24., 160.,  40.,   4.],
       [ 36., 160.,  40.,   3.],
       [ 24., 180.,  40.,   3.],
       [ 36., 180.,  40.,   4.]])

array([[ 24., 160.,  35.,   4.],
       [ 36., 160.,  35.,   3.],
       [ 24., 180.,  35.,   3.],
       [ 36., 180.,  35.,   4.],
       [ 24., 160.,  40.,   3.],
       [ 36., 160.,  40.,   4.],
       [ 24., 180.,  40.,   4.],
       [ 36., 180.,  40.,   3.]])

8 8


In [34]:
# seu código
df1 = pd.DataFrame(data={'Qtd_Fermento':D[:,0],'Temperatura':D[:,1],'Tempo':D[:,2],'Ovos':D[:,3]})
df2 = pd.DataFrame(data={'Qtd_Fermento':D2[:,0],'Temperatura':D2[:,1],'Tempo':D2[:,2],'Ovos':D2[:,3]})


In [35]:
df_final = pd.DataFrame()
df_final =pd.concat([df1,df2])

In [36]:
df_final

Qtd_Fermento  Temperatura  Tempo  Ovos
0          24.0        160.0   35.0   3.0
1          36.0        160.0   35.0   4.0
2          24.0        180.0   35.0   4.0
3          36.0        180.0   35.0   3.0
4          24.0        160.0   40.0   4.0
5          36.0        160.0   40.0   3.0
6          24.0        180.0   40.0   3.0
7          36.0        180.0   40.0   4.0
0          24.0        160.0   35.0   4.0
1          36.0        160.0   35.0   3.0
2          24.0        180.0   35.0   3.0
3          36.0        180.0   35.0   4.0
4          24.0        160.0   40.0   3.0
5          36.0        160.0   40.0   4.0
6          24.0        180.0   40.0   4.0
7          36.0        180.0   40.0   3.0

### Desafio: Gere 2 dataframes complementares, de forma que não haja nenhuma repetição de linhas

In [37]:
# seu código
df_final.drop_duplicates()

Qtd_Fermento  Temperatura  Tempo  Ovos
0          24.0        160.0   35.0   3.0
1          36.0        160.0   35.0   4.0
2          24.0        180.0   35.0   4.0
3          36.0        180.0   35.0   3.0
4          24.0        160.0   40.0   4.0
5          36.0        160.0   40.0   3.0
6          24.0        180.0   40.0   3.0
7          36.0        180.0   40.0   4.0
0          24.0        160.0   35.0   4.0
1          36.0        160.0   35.0   3.0
2          24.0        180.0   35.0   3.0
3          36.0        180.0   35.0   4.0
4          24.0        160.0   40.0   3.0
5          36.0        160.0   40.0   4.0
6          24.0        180.0   40.0   4.0
7          36.0        180.0   40.0   3.0